resources:
  repositories:
  - repository: templates
    type: github
    name: snw55/devops-templates
    ref: refs/heads/feature/lifecycle
    endpoint: snw55

trigger:
- "*"

stages:
- template: /pipelines/stages/lifecycle.yml@templates
  parameters:
    buildSteps:
      - powershell: Write-Host Build

    testJobs:
      - job: UnitTests
        pool:
          vmImage: ubuntu-latest
        steps:
        - powershell: Write-Host Test

    deploySteps:
      - checkout: templates
      - powershell: Write-Host Deploy
