resources:
  repositories:
  - repository: templates
    type: github
    name: snw55/devops-templates
    ref: refs/heads/feature/template-issue
    endpoint: snw55

trigger:
- "*"

extends:
  template: /pipelines/stages/lifecycle.yml@templates
  parameters:
    buildSteps:
    - powershell: Write-Host Build

    testJobs:
    - job: UnitTests
      pool:
        vmImage: ubuntu-latest
      steps:
      - powershell: Write-Host Test

    deploySteps:
      - checkout: templates
      - task: AzurePowerShell@4
        inputs:
          azureSubscription: foo
          scriptType: inlineScript
          inline: Write-Host Deploy
